from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('set-timezone/', views.set_timezone, name='set_timezone'),
    path('notifications/mark-read/', views.mark_notifications_read, name='mark_notifications_read'),
    path('login/', views.login, name='login'),
    path('check-username/', views.check_username, name='check_username'),
    
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    
    path('register/', views.register, name='register'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/calendar', views.calendar, name='calendar'),
    path('dashboard/income', views.income_visualization, name='income_visualization'),
    path('dashboard/budgets', views.budget_tracking, name='budget_tracking'),
    path('dashboard/projects/<int:project_id>/budget/', views.project_budget, name='project_budget'),
    path('dashboard/users', views.users, name='users'),
    path('dashboard/finance/create/', views.create_finance_transaction, name='create_finance_transaction'),
    path('dashboard/finance/<int:transaction_id>/update/', views.update_finance_transaction, name='update_finance_transaction'),
    path('dashboard/employees', views.employees, name='employees'),
    path('dashboard/employees/create/', views.create_employee, name='create_employee'),
    path('dashboard/employees/assign-project/', views.assign_employee_project, name='assign_employee_project'),
    path('dashboard/tasks', views.tasks, name='tasks'),
    path('dashboard/tasks/create/', views.create_task, name='create_task'),
    path('dashboard/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('dashboard/tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    path('dashboard/tasks/<int:task_id>/status/', views.update_task_status, name='update_task_status'),
    path('dashboard/tasks/<int:task_id>/comments/add/', views.add_task_comment, name='add_task_comment'),
    path('dashboard/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('dashboard/projects/create/', views.create_project, name='create_project'),
    path('dashboard/projects/<int:project_id>/update/', views.update_project, name='update_project'),
    path('dashboard/projects/<int:project_id>/team/', views.manage_project_team, name='manage_project_team'),
    path('dashboard/projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('dashboard/projects/<int:project_id>/files/upload/', views.upload_project_file, name='upload_project_file'),
    path('dashboard/projects/files/<int:file_id>/download/', views.download_project_file, name='download_project_file'),
    path('dashboard/projects/<int:project_id>/expenses/add/', views.add_project_expense, name='add_project_expense'),
    path('dashboard/projects/<int:project_id>/expense-categories/create/', views.create_expense_category, name='create_expense_category'),
    path('dashboard/projects', views.projects, name='projects'),
    path('dashboard/projects/<int:project_id>/', views.project_board, name='project_board'),
    path('dashboard/settings', views.settings_view, name='settings'),
    path('dashboard/settings/avatar/', views.upload_settings_avatar, name='upload_settings_avatar'),
    
    path('logout/', views.logout, name='logout'),
]
